# Jekyll configuration

name: LISA's BLOG
description: 마리 엄마는 개발자<br/>마리야 대신 코딩해줘...

# url is currently only used only for the RSS feed in feed.xml
url: https://lissapark91.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%Y-%m-%d"
  archive: "%m-%d"
  categories: "%Y-%m"
  tag: "%Y-%m"
# Language
lan: "en" 

# pagination:
#   enabled: true
#   per_page: 6
#   permalink: '/page:num/'
#   title: ' - page :num'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
paginate: 6

# autopages:
#   enabled: false

highlighter: rouge
markdown: kramdown

# gems: ['jekyll-paginate-v2']
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
